global:
    resolve_timeout: 1m
    slack_api_url: '{{ .Values.slack_hook_url }}'
  route:
     group_wait: 10s
     group_interval: 30s
     repeat_interval: 30m
     receiver: "telegram"
     routes:
       - receiver: "telegram"
         group_wait: 10s
         match_re:
           severity: critical|warning
         continue: true
  receivers:
   - name: "telegram"
     telegram_configs:
       - send_resolved: true
         bot_token: {{ .Values.bot_token }}
         chat_id: {{ .Values.chat_id }}
         parse_mode: 'Markdown'
         message: "016-032 \n{{ "{{" }} range .Alerts {{ "}}" }}{{ "{{" }} .Annotations.summary {{ "}}" }}\n{{ "{{" }} .Annotations.description }}\n{{ "{{" }} end {{ "}}" }}"