stages:
  - triggers

trigger_backend:
  stage: triggers
  trigger:
    include: 
      - "kubernetes/.gitlab-ci.yml"
    strategy: depend 
  rules:
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event"'
      changes:
        - kubernetes/**/*
