backend:
  # Вместо latest правильнее использовать версию .Chart.AppVersion в шаблоне
  image: gitlab.praktikum-services.ru:5050/std-016-032/sausage-store/sausage-backend
  replicas: 2
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 20%
  vault:
    host: std-016-32.praktikum-services.tech
    token: aHZzLkNBRVNJTENZTDFIRGRuclY5TmFTNjk4X3JsVmdyb2pxNHpTOHl0Q1M2WWpMelYxVUdoNEtIR2gyY3k1d1RYTTNNRUZKZFRNM1FraFROMk54VlVObWVrRmtURTg=
  dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImMzUmtMVEF4Tmkwd016STZUM0V6VWpFMU5XZz0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9Cg==