---
apiVersion: v1
kind: Secret
metadata:
  name: backend
  labels:
    app: backend
data:
  host: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYi16cGw0a202bnkyaW1iMnhmLm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDE2LTAzMgo=
  username: c3RkLTAxNi0wMzIK
  password: VGVzdHVzcjEyMzQK
type: Opaque

# серкерт для vault
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: backend
data:
  vault_token: aHZzLkNBRVNJTENZTDFIRGRuclY5TmFTNjk4X3JsVmdyb2pxNHpTOHl0Q1M2WWpMelYxVUdoNEtIR2gyY3k1d1RYTTNNRUZKZFRNM1FraFROMk54VlVObWVrRmtURTg=
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImMzUmtMVEF4Tmkwd016STZUM0V6VWpFMU5XZz0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9Cg==
type: kubernetes.io/dockerconfigjson 
