---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: backend
data:
  vault_token: {{.Values.backend.vault.token}}
type: Opaque

---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: {{ .Values.backend.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson 
